### ISSUE TITLE
feature request: Add non-expiring "latest" URLS

### ISSUE THREAD

**Issue by yourpalal** [krautcomputing/rubydocs#8]
duckduckgo has a !rubydocs [bang search](https://duckduckgo.com/bang?q=) for this site which points https://rubydocs.org/d/ruby-2-3-1/?q= , Unfortunately, this no longer works because the ruby 2.3.1 docs seem to have been dropped.

In fact, this !bang will break periodically as whatever version it refers to is dropped from the index. It would be great if there were a URL like https://rubydocs.org/d/ruby-latest that we could point duckduckgo at that will be vaild for as long as the site exists!

BTW, thanks for the site, it's very helpful!!

**Comment by manuelmeurer** [comment]
Ha, that's pretty awesome! 😄
Do you know who created the bang? Is there a way to find out?

Actually, the docs for Ruby 2.3.1 haven't been dropped (all docs will stay up forever), it was just an error in the way the URL was parsed. I fixed it, so the link should work again.

Something like https://rubydocs.org/d/ruby-latest is a good idea though!
I'll put it on my todo list. 😉 
How can we update the bang when it's done?

**Comment by yourpalal** [comment]
I tested the fix and it is indeed working again! Thanks for the speedy work!

I'm not sure who initially added the bang. It's actually how I found the
website, but it had the search parameter a bit wrong, so I updated it at
some point.

It's very easy to update them, you can just submit it to
https://duckduckgo.com/newbang then they'll review it and do the update.

Thanks again!

Le mar. 9 oct. 2018 05:55, Manuel Meurer <notifications@github.com> a
écrit :

**Comment by manuelmeurer** [comment]
@yourpalal https://rubydocs.org/d/ruby-latest works now (just like https://rubydocs.org/d/rails-latest and any-other-project-latest). 😄 
I resubmitted the bangs to DDG.
Thanks again for the idea!

**Comment by yourpalal** [comment]
Awesome!! I'll be sure to use the rails one too :) Thanks for the great
website!
